


# Numpy array Indexing and slicing 

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3])
print(arr)
print(arr.ndim)
print(arr[1])

[1 2 3]
1
2


In [4]:
arr=np.array([1,2,3])
print(arr)
print(arr.ndim)
print(arr[-1])

[1 2 3]
1
3


In [25]:
print('ARRAY SLICING ')
arr=np.arange(1,20)
print(arr)
print(arr[0:5:1])
print(arr[: : -1])
print()
print(arr[: : -2])
print(arr[11:0:-1])
print(arr[11:0:-2])


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2 3 4 5]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]

[19 17 15 13 11  9  7  5  3  1]
[12 11 10  9  8  7  6  5  4  3  2]
[12 10  8  6  4  2]
[]


In [29]:
print('ARRAY INDEXING')
arr=np.arange(1,20)
print(arr)
print(arr[1])

ARRAY INDEXING
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
2


In [37]:
print('ARRAY INDEXING')
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
print(arr[0,1])

ARRAY INDEXING
[[1 2 3]
 [4 5 6]]
2
2


In [38]:
print('ARRAY INDEXING')
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
print(arr[0,0: : 1])

ARRAY INDEXING
[[1 2 3]
 [4 5 6]]
2
[1 2 3]
