In [2]:
import numpy as np


In [8]:
arr=np.array([1,2,3])
print(arr)
print(arr.shape)

arr2=np.array([1,2,3])
print(arr2)
print(arr2.shape)


print(arr+arr2)

[1 2 3]
(3,)
[1 2 3]
(3,)
[2 4 6]


In [10]:
arr=np.array([1,2,3])
print(arr)
print(arr.shape)

arr2=np.array([1,2,3,4])
print(arr2)
print(arr2.shape)


print(arr+arr2)

[1 2 3]
(3,)
[1 2 3 4]
(4,)


ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [13]:
arr=np.array([1,2,3])
print(arr)
print(arr.shape)

arr2=np.array([[1],
              [2],
              [3],
              [4]])
print(arr2)
print(arr2.shape)


print(arr+arr2)

[1 2 3]
(3,)
[[1]
 [2]
 [3]
 [4]]
(4, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


In [16]:
arr=np.array([1,2,3],ndmin=3)
print(arr)

[[[1 2 3]]]
