# Data types in numpy arrays

In [3]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.dtype)


[1 2 3 4 5]
<class 'numpy.ndarray'>
int32


In [9]:
arr=np.array([110,220,315,4,5])
print(arr.dtype)

int32


In [12]:
arr=np.array([1.0,2.0,3.3,4,5])

print(arr.dtype)

float64


In [23]:
arr=np.array(['salmanfaiziisabadboy','faizi','sarmin','ahmed'],dtype='U15')

print(arr.dtype)

<U15


In [16]:
arr=np.array(['f','s','x'])

print(arr.dtype)

<U1


In [19]:
arr=np.array(['farhan_noori','salman_faizi','xmas_tree'])

print(arr.dtype)

<U12


In [24]:
arr=np.array([1,2,3,4,5],dtype='f')

print(arr.dtype)

float32


In [31]:
arr=np.array([10,20,30,40,50])
print("Data type",arr.dtype)
print(arr)

print()

arr_f=np.float32(arr)
print("Data type",arr_f.dtype)
print(arr_f)

print()

arr_f2=np.int_(arr_f)
print("Data type",arr_f2.dtype)
print(arr_f2)

Data type int32
[10 20 30 40 50]

Data type float32
[10. 20. 30. 40. 50.]

Data type int32
[10 20 30 40 50]


In [38]:
arr=np.arange(2,10)
print(arr)
print(arr.dtype)
arr_f=arr.astype(float)
print(arr_f)
print(arr_f.dtype)

[2 3 4 5 6 7 8 9]
int32
[2. 3. 4. 5. 6. 7. 8. 9.]
float64
