In [2]:
import numpy as np

In [29]:
arr=np.array([1,2,3,4,5])
print(arr)
# x=np.insert(arr,2,15)
# print(x)
print()

x=np.insert(arr,(2,3),15)
print(x)
print()
x=np.insert(arr,(2,3),(15,20))
print(x)
print()


[1 2 3 4 5]

[ 1  2 15  3 15  4  5]

[ 1  2 15  3 20  4  5]



In [30]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
# x=np.insert(arr,2,15)
# print(x)
print()

x=np.insert(arr,(0,1),15,axis=1)
print(x)
print()
x=np.insert(arr,(0,1),(15,20,25),axis=0)
print(x)
print()

[[1 2 3]
 [4 5 6]]

[[15  1 15  2  3]
 [15  4 15  5  6]]

[[15 20 25]
 [ 1  2  3]
 [15 20 25]
 [ 4  5  6]]



# Delete function

In [32]:
arr=np.array([1,2,3,4,5])
x=np.delete(arr,[2])
print(x)

[1 2 4 5]
