In [2]:
import numpy as np

In [6]:
arr=np.array([1,2,3,4,5])
print(arr)
arr2=np.array([6,7,8,9,10])
print(arr2)

join=np.concatenate([arr,arr2])
print(join)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
print("joining 2D arrays")
arr=np.array([[1,2,3,4,5],[5,4,3,2,1]])
print(arr)
arr2=np.array([[6,7,8,9,10],[10,9,8,7,6]])
print(arr2)

join=np.concatenate([arr,arr2],axis=1)
print(join)

print()
print("joining 2d array on axis 0")
print("joining 2D arrays")
arr=np.array([[1,2,3,4,5],[5,4,3,2,1]])
print(arr)
arr2=np.array([[6,7,8,9,10],[10,9,8,7,6]])
print(arr2)

join=np.concatenate([arr,arr2],axis=0)
print(join)

joining 2D arrays
[[1 2 3 4 5]
 [5 4 3 2 1]]
[[ 6  7  8  9 10]
 [10  9  8  7  6]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 5  4  3  2  1 10  9  8  7  6]]

joining 2d array on axis 0
joining 2D arrays
[[1 2 3 4 5]
 [5 4 3 2 1]]
[[ 6  7  8  9 10]
 [10  9  8  7  6]]
[[ 1  2  3  4  5]
 [ 5  4  3  2  1]
 [ 6  7  8  9 10]
 [10  9  8  7  6]]


In [15]:
print("Stack function of numpy to join arrays ")
arr=np.array([1,2,3,4,5])
print(arr)
arr2=np.array([6,7,8,9,10])
print(arr2)

join=np.stack([arr,arr2])
print(join)

print()
join=np.hstack([arr,arr2])
print(join)

print()
join=np.vstack([arr,arr2])
print(join)

print()
join=np.dstack([arr,arr2])
print(join)

Stack function of numpy to join arrays 
[1 2 3 4 5]
[ 6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[ 1  2  3  4  5  6  7  8  9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]
