In [2]:
import numpy as np


In [5]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)
for i in arr:
    print(i)

[1 2 3 4 5]
1
1
2
3
4
5


In [9]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr.ndim)
for i in arr:
    print(i)
    
for i in arr:
    for j in i:
        print(j)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
[1 2 3 4 5]
[ 6  7  8  9 10]
1
2
3
4
5
6
7
8
9
10


In [12]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr.ndim)
for i in arr:
    print(i)
    
for i in arr:
    for j in i:
        print(j)
print("......................................")       
        
for i in np.nditer(arr):
    print(i)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
[1 2 3 4 5]
[ 6  7  8  9 10]
1
2
3
4
5
6
7
8
9
10
......................................
1
2
3
4
5
6
7
8
9
10


In [14]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr.ndim)
for i in arr:
    print(i)
    
for i in arr:
    for j in i:
        print(j)
print("......................................")       
        
for i in np.nditer(arr,flags=["buffered"],op_dtypes=['S']):
    print(i)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
[1 2 3 4 5]
[ 6  7  8  9 10]
1
2
3
4
5
6
7
8
9
10
......................................
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'


In [18]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr.ndim)

print("......................................")       
        
for i in np.nditer(arr,flags=["buffered"],op_dtypes=['S']):
    print(i)

print("indexes and data using ndenumurate function ")
for i,j in np.ndenumerate(arr):
    print(i,j)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
......................................
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
indexes and data using ndenumurate function 
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9
(1, 4) 10
