# metrix


In [3]:
import numpy as np


In [10]:
metrix=np.matrix([[1,2,3],[4,5,6]])
print(metrix)

[[1 2 3]
 [4 5 6]]


In [13]:
metrix=np.matrix([[1,2,3],[4,5,6]])
print(metrix*2)
print()

metrix=np.matrix([[1,2,3],[4,5,6]])
print(metrix+2)
print()
metrix=np.matrix([[1,2,3],[4,5,6]])
print(metrix/2)
print()

print("only the multiplication is different from a numpy array")
# metrix=np.matrix([[1,2,3],[4,5,6]])
# print(metrix*metrix)
# print()

[[ 2  4  6]
 [ 8 10 12]]

[[3 4 5]
 [6 7 8]]

[[0.5 1.  1.5]
 [2.  2.5 3. ]]



ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [22]:
print("metrix multiplication using .dot function")
metrix=np.matrix([[1,2,3],[4,5,6],[8,9,10]])
print(metrix.dot(metrix))
print()

metrix multiplication using .dot function
[[ 33  39  45]
 [ 72  87 102]
 [124 151 178]]



# Arrays

In [20]:
arr=np.array([[1,2,4],[4,5,6]])
print(arr)

print(arr*2)
print()
print(arr*+2)
print()
print(arr-2)
print()
print(arr*arr)
print()

[[1 2 4]
 [4 5 6]]
[[ 2  4  8]
 [ 8 10 12]]

[[ 2  4  8]
 [ 8 10 12]]

[[-1  0  2]
 [ 2  3  4]]

[[ 1  4 16]
 [16 25 36]]

