# Numpy arrays of different dimensions

In [2]:
print("Salman Faizi")

Salman Faizi


In [3]:
import numpy as np


In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
x=[10,20,30,40,50]
y=np.array(x)
y
print(type(y))
print(y.ndim)

<class 'numpy.ndarray'>
1


In [6]:
list=[]
for i in range(1,5):
    inp=int(input("Enter vlaue: "))
    list.append(inp)
x=np.array(list)
x

Enter vlaue: 10
Enter vlaue: 20
Enter vlaue: 30
Enter vlaue: 40


array([10, 20, 30, 40])

In [10]:
arr2=[[10,20,30,40,50],[10,20,30,40,50]]
x=np.array(arr2)
print(x)
print(type(x))
print(x.ndim)

[[10 20 30 40 50]
 [10 20 30 40 50]]
<class 'numpy.ndarray'>
2


In [12]:
arr3=[[[10,20,30,40,50],[10,20,30,40,50]]]
x=np.array(arr3)
print(x)
print(type(x))
print(x.ndim)

[[[10 20 30 40 50]
  [10 20 30 40 50]]]
<class 'numpy.ndarray'>
3


In [13]:
arr10=np.array([10,20,30,40,50],ndmin=10)
print(arr10)
print(type(arr10))
print(arr10.ndim)

[[[[[[[[[[10 20 30 40 50]]]]]]]]]]
<class 'numpy.ndarray'>
10
