# Search

In [1]:
import numpy as np


In [21]:

arr=np.array([1,2,3,4,5,6,7,4,3,2,4,5,3,2,2,4,5,5,6,7,8,4])
print(arr)
print("Searches a perticular element in the array and returns the index ")
x=np.where(arr==2)
print(x)
print()
y=np.where(arr%2==0)
print(y)

[1 2 3 4 5 6 7 4 3 2 4 5 3 2 2 4 5 5 6 7 8 4]
Searches a perticular element in the array and returns the index 
(array([ 1,  9, 13, 14], dtype=int64),)

(array([ 1,  3,  5,  7,  9, 10, 13, 14, 15, 18, 20, 21], dtype=int64),)


# Search_Sort array

In [32]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
x=np.searchsorted(arr,5)
print(x)
print()
x=np.searchsorted(arr,11)
print(x)
print()

x=np.searchsorted(arr,1,side="right")
print(x)

[ 1  2  3  4  5  6  7  8  9 10]
4

10

1


# Sort array

In [36]:
arr=np.array([1,43,2,4,5,53,2,1,0])
sort=np.sort(arr)
print(sort)

arr=np.array(['a','s','d','f'])
sort=np.sort(arr)
print(sort)

[ 0  1  1  2  2  4  5 43 53]
['a' 'd' 'f' 's']


# Filter array

In [49]:
arr=np.array([1,2,3,4,5])
f=[True,False,True,False,True]
arr_new=arr[f]
print(arr_new)
print(type(arr_new))

print("this method doesn't work when there is lower element(true,false) than the original array")

[1 3 5]
<class 'numpy.ndarray'>
this method doesn't work when there is lower element(true,false) than the original array


IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 4