# shape

In [5]:
import numpy as np

In [10]:
arr=np.arange(1,10)
print(arr)
print(arr.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


In [13]:
arr=np.eye(2)
print(arr)
print(arr.shape)

[[1. 0.]
 [0. 1.]]
(2, 2)


In [15]:
arr=np.array([1,2,3,4],ndmin=4)
print(arr)
print(arr.shape)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


# reshaping of numpy array

In [22]:
arr=np.arange(1,7)
print(arr)
print(arr.ndim)


print()


x=arr.reshape(3,2)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [24]:
arr=np.arange(1,28)
print(arr)
print(arr.ndim)

print()

x=arr.reshape(3,3,3)
print(x)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
1

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
3


In [27]:
arr=np.arange(1,28)
print(arr)
print(arr.ndim)

print()

x=arr.reshape(3,3,3)
print(x)
print(x.ndim)

print()


print("-1 or (27, ) both works similar")
x2=x.reshape(27,)
print(x2)
print(x2.ndim)


print()


x2=x.reshape(-1)
print(x2)
print(x2.ndim)




[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
1

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
3

-1 or (27, ) both works similar
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
1

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
1
