In [2]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5,6])
print(arr)
split=np.array_split(arr,3)
print(split)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [10]:
arr=np.array([1,2,3,4,5,6])
print(arr)
split=np.array_split(arr,8)
print(split)

[1 2 3 4 5 6]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32)]


In [14]:
arr=np.array([[1,2],[3,4],[5,6]])
print(arr)
split=np.array_split(arr,3,axis=1)

print(split)
print()
split=np.array_split(arr,3,axis=0)
print(split)

[[1 2]
 [3 4]
 [5 6]]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
